# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Modul1_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from ctypes.wintypes import RGB
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QImage, QColor, QPixelFormat
from PyQt5.QtWidgets import QFileDialog, QMessageBox, QAction, QMainWindow, QSlider, QPushButton, QToolTip, QApplication
from PIL import Image, ImageOps, ImageEnhance, ImageColor
from PIL.ImageQt import ImageQt
import cv2
import numpy as np

class Ui_MainModul1(object):
    def setupUi(self, MainModul1):
        MainModul1.setObjectName("MainModul1")
        MainModul1.resize(662, 595)
        self.centralwidget = QtWidgets.QWidget(MainModul1)
        self.centralwidget.setObjectName("centralwidget")
        self.btnCopy = QtWidgets.QPushButton(self.centralwidget)
        self.btnCopy.setGeometry(QtCore.QRect(350, 230, 75, 23))
        self.btnCopy.setObjectName("btnCopy")
        self.btnGreen = QtWidgets.QRadioButton(self.centralwidget)
        self.btnGreen.setGeometry(QtCore.QRect(130, 510, 80, 18))
        self.btnGreen.setObjectName("btnGreen")
        self.btnOpen = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpen.setGeometry(QtCore.QRect(230, 230, 75, 23))
        self.btnOpen.setObjectName("btnOpen")
        self.btnCyan = QtWidgets.QRadioButton(self.centralwidget)
        self.btnCyan.setGeometry(QtCore.QRect(400, 510, 80, 18))
        self.btnCyan.setObjectName("btnCyan")
        self.gambarRGB = QtWidgets.QLabel(self.centralwidget)
        self.gambarRGB.setGeometry(QtCore.QRect(70, 350, 191, 151))
        self.gambarRGB.setAutoFillBackground(False)
        self.gambarRGB.setFrameShape(QtWidgets.QFrame.Panel)
        self.gambarRGB.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gambarRGB.setText("")
        self.gambarRGB.setScaledContents(True)
        self.gambarRGB.setObjectName("gambarRGB")
        self.btnYellow = QtWidgets.QRadioButton(self.centralwidget)
        self.btnYellow.setGeometry(QtCore.QRect(540, 510, 80, 18))
        self.btnYellow.setObjectName("btnYellow")
        self.gambarAsli = QtWidgets.QLabel(self.centralwidget)
        self.gambarAsli.setGeometry(QtCore.QRect(200, 70, 261, 151))
        self.gambarAsli.setAutoFillBackground(False)
        self.gambarAsli.setFrameShape(QtWidgets.QFrame.Panel)
        self.gambarAsli.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gambarAsli.setText("")
        self.gambarAsli.setScaledContents(True)
        self.gambarAsli.setObjectName("gambarAsli")
        self.gambarCMY = QtWidgets.QLabel(self.centralwidget)
        self.gambarCMY.setGeometry(QtCore.QRect(400, 350, 191, 151))
        self.gambarCMY.setAutoFillBackground(False)
        self.gambarCMY.setFrameShape(QtWidgets.QFrame.Panel)
        self.gambarCMY.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gambarCMY.setText("")
        self.gambarCMY.setScaledContents(True)
        self.gambarCMY.setObjectName("gambarCMY")
        self.btnBlue = QtWidgets.QRadioButton(self.centralwidget)
        self.btnBlue.setGeometry(QtCore.QRect(190, 510, 80, 18))
        self.btnBlue.setObjectName("btnBlue")
        self.btnMagenta = QtWidgets.QRadioButton(self.centralwidget)
        self.btnMagenta.setGeometry(QtCore.QRect(460, 510, 80, 18))
        self.btnMagenta.setObjectName("btnMagenta")
        self.labelCitraAsli = QtWidgets.QLabel(self.centralwidget)
        self.labelCitraAsli.setGeometry(QtCore.QRect(290, 30, 81, 21))
        self.labelCitraAsli.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelCitraAsli.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCitraAsli.setObjectName("labelCitraAsli")
        self.btnRed = QtWidgets.QRadioButton(self.centralwidget)
        self.btnRed.setGeometry(QtCore.QRect(80, 510, 80, 18))
        self.btnRed.setObjectName("btnRed")
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(290, 260, 75, 23))
        self.btnExit.setObjectName("btnExit")
        self.labelCitraRGB = QtWidgets.QLabel(self.centralwidget)
        self.labelCitraRGB.setGeometry(QtCore.QRect(120, 310, 81, 21))
        self.labelCitraRGB.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelCitraRGB.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCitraRGB.setObjectName("labelCitraRGB")
        self.labelCitraCMY = QtWidgets.QLabel(self.centralwidget)
        self.labelCitraCMY.setGeometry(QtCore.QRect(460, 310, 81, 21))
        self.labelCitraCMY.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelCitraCMY.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCitraCMY.setObjectName("labelCitraCMY")
        MainModul1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainModul1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 662, 21))
        self.menubar.setDefaultUp(True)
        self.menubar.setObjectName("menubar")
        self.menuModul1 = QtWidgets.QMenu(self.menubar)
        self.menuModul1.setObjectName("menuModul1")
        MainModul1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainModul1)
        self.statusbar.setObjectName("statusbar")
        MainModul1.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainModul1)
        self.actionNew.setObjectName("actionNew")
        self.menuModul1.addAction(self.actionNew)
        self.menuModul1.addSeparator()
        self.menubar.addAction(self.menuModul1.menuAction())

        self.retranslateUi(MainModul1)
        self.btnOpen.clicked.connect(self.loadImage)
        self.btnCopy.clicked.connect(self.copyImage)
        # self.exitButton.clicked.connect(lambda:self.close())
        self.btnRed.clicked.connect(self.convertRed)
        self.btnGreen.clicked.connect(self.convertGreen)
        self.btnBlue.clicked.connect(self.convertBlue)
        self.btnCyan.clicked.connect(self.convertCyan)
        self.btnMagenta.clicked.connect(self.convertMagenta)
        self.btnYellow.clicked.connect(self.convertYellow)
        QtCore.QMetaObject.connectSlotsByName(MainModul1)

    def retranslateUi(self, MainModul1):
        _translate = QtCore.QCoreApplication.translate
        MainModul1.setWindowTitle(_translate("MainModul1", "Praktikum Pengolahan Citra Digital"))
        self.btnCopy.setText(_translate("MainModul1", "Copy"))
        self.btnGreen.setText(_translate("MainModul1", "Green"))
        self.btnOpen.setText(_translate("MainModul1", "Open"))
        self.btnCyan.setText(_translate("MainModul1", "Cyan"))
        self.btnYellow.setText(_translate("MainModul1", "Yellow"))
        self.btnBlue.setText(_translate("MainModul1", "Blue"))
        self.btnMagenta.setText(_translate("MainModul1", "Magenta"))
        self.labelCitraAsli.setText(_translate("MainModul1", "Citra Asli"))
        self.btnRed.setText(_translate("MainModul1", "Red"))
        self.btnExit.setText(_translate("MainModul1", "Exit"))
        self.labelCitraRGB.setText(_translate("MainModul1", "Citra RGB"))
        self.labelCitraCMY.setText(_translate("MainModul1", "Citra CMY"))
        self.menubar.setStatusTip(_translate("MainModul1", "Modul1"))
        self.menuModul1.setTitle(_translate("MainModul1", "File"))
        self.actionNew.setText(_translate("MainModul1", "New"))

    def loadImage(self):
        self.namaImg, typeimg= QFileDialog.getOpenFileName(self.centralwidget, "Open Image", "", "*.png;*.jpg;;*.bmp;;All Files(*)")
        jpg = QPixmap(self.namaImg)

        self.gambarAsli.setPixmap(jpg)

    def copyImage(self):
        img = Image.open(self.namaImg)
        width, height= img.size

        for row in range(height):
            for col in range(width):
                img.getpixel((col,row))

        img.save("copyImage.jpg")     
        jpg=QPixmap("copyImage.jpg")
        self.gambarRGB.setPixmap(jpg)

    def convertRed(self):
        img = cv2.imread(self.namaImg, cv2.IMREAD_UNCHANGED)
        print(img.shape)

        red_channel = img[:,:,2]
        red_img = np.zeros(img.shape)
        red_img[:,:,2] = red_channel

        cv2.imwrite("convertResult.jpg", red_img) 
        jpg=QPixmap("convertResult.jpg")
        self.gambarRGB.setPixmap(jpg)
        
    def convertGreen(self):
        img = cv2.imread(self.namaImg, cv2.IMREAD_UNCHANGED)
        print(img.shape)
        #BGR, 0=blue, 1=Greed, 2=Blue
        green_channel = img[:,:,1]
        green_img = np.zeros(img.shape)
        green_img[:,:,1] = green_channel

        cv2.imwrite("convertResult.jpg", green_img) 
        jpg=QPixmap("convertResult.jpg")
        self.gambarRGB.setPixmap(jpg)

    def convertBlue(self):
        img = cv2.imread(self.namaImg, cv2.IMREAD_UNCHANGED) 
        print(img.shape)
        blue_channel = img[:,:,0] 
        blue_img = np.zeros(img.shape)
        blue_img[:,:,0] = blue_channel 

        #save image
        cv2.imwrite("convertResult.jpg", blue_img) 
        jpg=QPixmap("convertResult.jpg")
        self.gambarRGB.setPixmap(jpg)
        
    def convertCyan(self):
        img = cv2.imread(self.namaImg, cv2.IMREAD_UNCHANGED)
        print(img.shape)
        
        img[:,:,2] = np.zeros([img.shape[0], img.shape[1]])

        #save image
        cv2.imwrite("convertResult.jpg", img) 
        jpg=QPixmap("convertResult.jpg")
        self.gambarCMY.setPixmap(jpg)
    
    def convertMagenta(self):
        img = cv2.imread(self.namaImg, cv2.IMREAD_UNCHANGED)
        print(img.shape)

        img[:,:,1] = np.zeros([img.shape[0], img.shape[1]])

        #save image
        cv2.imwrite("convertResult.jpg", img) 
        jpg=QPixmap("convertResult.jpg")
        self.gambarCMY.setPixmap(jpg)
    
    def convertYellow(self):
        img = cv2.imread(self.namaImg, cv2.IMREAD_UNCHANGED)
        print(img.shape)
        img[:,:,0] = np.zeros([img.shape[0], img.shape[1]])

        #save image
        cv2.imwrite("convertResult.jpg", img) 
        jpg=QPixmap("convertResult.jpg")
        self.gambarCMY.setPixmap(jpg)
    
    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainModul1 = QtWidgets.QMainWindow()
    ui = Ui_MainModul1()
    ui.setupUi(MainModul1)
    MainModul1.show()
    sys.exit(app.exec_())
